import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./styles/globals.css";
import Providers from "@/components/providers";
import { Header } from "@/components/sections/header";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <Providers>
          <Header />
          {/* <Banner /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
